### ISSUE TITLE
Fanart background Issue

### ISSUE THREAD

**Issue by DJMix-I-Can** [drinfernoo/seren.theme.az2#6]
What's up... 
I encountered this issue awhile back with the 0.3.0 & never looked into it or made an issue about it.
I just rolled it back to 0.2.0 & moved on. The only way I knew there was update to your theme is because I checked on your github account. If I go to themes in Seren & click on "check for updates", I always get "There are currently no updates available." The check for theme update doesn't work.
The main issue after 0.2.0 is that I wasn't getting the fanart background when it was scraping. I was getting [this](https://imgur.com/GnUMfPB). I finally decided to play with it to see if I could figure it out. I thought It had something to do with my modifications of the skin. I did a fresh install & installed Seren & AZ2, nothing else.  It worked! So now, I started changing AZ2 settings to my specs, no mods, just settings. I'm not a fan of having fanart on the main home menu & prefer a dark theme, like [this](https://imgur.com/ioM4IIz). I went into AZ2 settings, background and [unchecked fanart](https://imgur.com/aeXbDsL). I rescraped the same movie & lost the fanart background again.
I know re-enabling fanart background will fix it but then I'll start getting the fanart on the home menu, which I don't want. The 0.2.0 version showed the fanart background on scrape regardless if the fanart background was enabled or not.
Thanks.
Edit: I'm not sure if there are different versions of the theme. I tried to look for the zips but didn't see any. The only versions I had were 0.20, 0.30 & 0.32 & only tested it on those.

**Comment by drinfernoo** [comment]
The reason this is happening is just because if "Fanart" is off in the skin, I just don't show anything. I can change that to showing the solid skin background instead, and it'll even be closer to the skin look 👍 For what it's worth, this tends to happen with items that *have* no fanart, or that just hasn't loaded in yet.

Also, 0.3.2 is the latest version, so if you were already on it, then checking for updates would do you no good 😅

**Comment by DJMix-I-Can** [comment]
No worries, I'll figure it out on my own.

**Comment by drinfernoo** [comment]
0.3.3 fixes this issue :+1: No fancy background effects yet, but I've got issues open for those already.
