### ISSUE TITLE
Not working any more 

### ISSUE THREAD

**Issue by Gioherk** [drinfernoo/seren.theme.az2#7]
With the new version of seren the addon is not working anymore.
Can you please fix it? 
Thanks

**Comment by drinfernoo** [comment]
This isn't an add-on, and you haven't told me what isn't working. I'm aware that this theme needs to be updated, but there currently are issues with Seren's theme engine. When those are resolved, I'll be able to continue development.

**Comment by Gioherk** [comment]
OK thanks for the explanation

**Comment by drinfernoo** [comment]
Also, it appears that it is working fine with Seren 2.0.8.
